---
# Group vars for all hosts

host: emailserver
domain: sparetiresllc.com
ip_address: "{{ ansible_default_ipv4.address }}"
mail_fqdn: "{{ host }}.{{ domain }}"
smtp_fqdn: "smtp.{{ domain }}"
imap_fqdn: imap.{{ domain }}
mail_user: ranoa
email_for_updates: "{{ mail_user }}@{{ domain }}"
